version: '3.8'

services:
  app:
    image: 'petclinic:latest'
    build:
      context: ./petclinic
    ports:
      - 8444:8444
    depends_on:
      - postgres
      - keycloak
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/petclinic
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
          
  postgres:
    image: 'postgres:${POSTGRES_VERSION}'
    volumes:
      - ./postgres/sql-init:/docker-entrypoint-initdb.d
      - ./postgres/db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=petclinic
      - PGDATA=/var/lib/postgresql/data/pgdata

  keycloak:
    image: jboss/keycloak:11.0.2
    ports:
      - 8443:8443
    volumes:
      - ./keycloak/certs:/etc/x509/https
      - ./keycloak/ca_certs:/var/ca_certs
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - X509_CA_BUNDLE=/var/ca_certs/petclinic.crt
    depends_on:
      - keycloak-postgres

  keycloak-postgres:
    image: 'postgres:${POSTGRES_VERSION}'
    volumes:
      - ./keycloak/kc_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
      - PGDATA=/var/lib/postgresql/data/pgdata
